# Generated by Django 4.2.1 on 2023-05-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-create_data', '-update_data'], 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name product'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name product'),
        ),
    ]
